using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Avalonia.Threading;
using CardVault.Data;
using CardVault.Models;
using CardVault.Security;

namespace CardVault.Services;

/// <summary>
/// Opt-in encrypted file sync. The whole vault (entries, folders, tombstones) is
/// serialized into a single snapshot that is sealed with a key derived from the
/// MASTER PASSWORD plus a dedicated sync salt. The salt is random, generated by the
/// first device that enables sync on a folder and baked into the snapshot header, so
/// every device with the same master password can decrypt regardless of its own
/// per-vault KDF parameters. The in-memory sync key is derived at unlock and zeroed
/// on lock — only usable while the vault is open.
///
/// Merges are last-writer-wins per entity by <c>updated_at</c>. Deletions are carried
/// as tombstones so an offline device does not silently resurrect a deleted item.
/// This is a peer-to-peer snapshot (no server); both devices simply point at the same
/// shared folder (Dropbox, OneDrive, SMB, ...).
/// </summary>
public sealed class SyncService
{
    public const string FolderKey = "sync_folder";
    public const string EnabledKey = "sync_enabled";
    public const string LastKey = "sync_last";
    public const string TombstonesKey = "sync_tombstones";
    public const string SaltKey = "sync_salt";
    public const string IterKey = "sync_iter";
    public const string DeviceKey = "sync_device";

    public const string FileName = "cardvault-sync.cvsync";
    public const string Magic = "CVSY";
    public const int FormatVersion = 1;
    public const int DefaultIterations = 210_000;

    private static readonly TimeSpan TimerInterval = TimeSpan.FromMinutes(5);
    private static readonly TimeSpan SkewTolerance = TimeSpan.FromMinutes(2);
    private static readonly TimeSpan TombstoneRetention = TimeSpan.FromDays(365);
    private const string SealContext = "CardVault::sync::v1";
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = false };

    private readonly VaultDatabase _db;
    private readonly VaultSession _session;
    private readonly DispatcherTimer _timer;
    private byte[]? _syncKey;
    private int _running;

    public SyncService(VaultDatabase db, VaultSession session)
    {
        _db = db;
        _session = session;
        _timer = new DispatcherTimer(TimerInterval, DispatcherPriority.Background, async (_, _) => await OnTickAsync());
        _session.Locked += OnLocked;
    }

    public void Start() => _timer.Start();

    public void Stop()
    {
        _timer.Stop();
        _session.Locked -= OnLocked;
    }

    public string LastError { get; private set; } = string.Empty;
    public DateTimeOffset? LastSuccess { get; private set; }

    // ============================= preferences =============================

    public SyncPrefs ReadPrefs() => new(
        _db.GetMeta(FolderKey) ?? string.Empty,
        _db.GetMeta(EnabledKey) == "1",
        ParseTimestamp(_db.GetMeta(LastKey)));

    public void SavePrefs(SyncPrefs prefs)
    {
        if (string.IsNullOrWhiteSpace(prefs.Folder))
        {
            _db.DeleteMeta(FolderKey);
            _db.DeleteMeta(EnabledKey);
            return;
        }

        _db.SetMeta(FolderKey, prefs.Folder.Trim());
        if (prefs.Enabled) _db.SetMeta(EnabledKey, "1");
        else _db.DeleteMeta(EnabledKey);
    }

    /// <summary>
    /// Copies the sync KDF parameters out of an existing snapshot header so a
    /// second device unlocks with the same sync key as the first. Returns true when
    /// the shared file exists and its header was adopted.
    /// </summary>
    public bool AdoptRemoteSalt(string folder)
    {
        if (string.IsNullOrWhiteSpace(folder)) return false;
        var path = Path.Combine(folder.Trim(), FileName);
        if (!File.Exists(path)) return false;

        try
        {
            var env = JsonSerializer.Deserialize<SyncEnvelope>(File.ReadAllBytes(path), JsonOptions);
            if (env is null || env.Magic != Magic || string.IsNullOrEmpty(env.KdfSalt) || env.KdfIterations <= 0) return false;
            _db.SetMeta(SaltKey, env.KdfSalt);
            _db.SetMeta(IterKey, env.KdfIterations.ToString());
            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>Derives the in-memory sync key. Call at unlock while the password is still available.</summary>
    public void OnUnlocked(string masterPassword)
    {
        ReleaseKey();

        var saltText = _db.GetMeta(SaltKey);
        byte[] salt;
        if (string.IsNullOrEmpty(saltText))
        {
            salt = CryptoService.RandomBytes(16);
            _db.SetMeta(SaltKey, Convert.ToBase64String(salt));
            _db.SetMeta(IterKey, DefaultIterations.ToString());
        }
        else
        {
            salt = Convert.FromBase64String(saltText);
        }

        var iterations = int.TryParse(_db.GetMeta(IterKey), out var v) && v > 0 ? v : DefaultIterations;
        _syncKey = CryptoService.DeriveKey(masterPassword, salt, iterations);
    }

    // ============================= sync =============================

    /// <summary>Main entry point: reads the shared snapshot, merges with local state and writes back when needed.</summary>
    public async Task<bool> RunSyncAsync()
    {
        if (Interlocked.Exchange(ref _running, 1) == 1) return false;
        try
        {
            var prefs = ReadPrefs();
            if (!prefs.Enabled || string.IsNullOrWhiteSpace(prefs.Folder)) return false;
            if (_syncKey is null) return false;

            var folder = prefs.Folder.Trim();
            var path = Path.Combine(folder, FileName);
            var now = DateTimeOffset.UtcNow;

            return await Task.Run(async () =>
            {
                var localEntries = new List<LocalItem>();
                foreach (var e in _db.ListEntries())
                    localEntries.Add(new LocalItem(e, EntryKinds.IsCard(e.Kind)
                        ? (object?)_db.DecryptCard(e)
                        : _db.DecryptEntry(e)));

                var localFolders = _db.ListFolders();

                var baseEntries = new List<SyncEntry>();
                var baseFolders = new List<SyncFolder>();
                var baseTombstones = new List<SyncTombstone>();

                if (File.Exists(path))
                {
                    var snapshot = Decode(File.ReadAllBytes(path));
                    baseEntries.AddRange(snapshot.Entries);
                    baseFolders.AddRange(snapshot.Folders);
                    baseTombstones.AddRange(snapshot.Tombstones);
                }

                var merge = Merge(localEntries, localFolders, LoadTombstones(),
                    baseEntries, baseFolders, baseTombstones, prefs.LastSync, now);

                if (merge.Changed) Apply(merge);

                if (!File.Exists(path) || merge.Changed)
                {
                    Directory.CreateDirectory(folder);
                    var bytes = Encode(BuildSnapshot(merge, DeviceId(), now));
                    WriteAtomically(path, bytes);
                    _db.SetMeta(LastKey, now.ToString("O"));
                    LastSuccess = now;
                }

                LastError = string.Empty;
                return merge.Changed;
            });
        }
        catch (Exception ex)
        {
            LastError = ex.Message;
            throw;
        }
        finally
        {
            Interlocked.Exchange(ref _running, 0);
        }
    }

    /// <summary>
    /// Pure LWW merge. Returns the state that must exist locally plus the tombstones
    /// to propagate. Deterministic given the same inputs, so both devices converge.
    /// </summary>
    internal static SyncMergeResult Merge(
        IReadOnlyList<LocalItem> localEntries,
        IReadOnlyList<Folder> localFolders,
        IReadOnlyList<SyncTombstone> localTombstones,
        IReadOnlyList<SyncEntry> baseEntries,
        IReadOnlyList<SyncFolder> baseFolders,
        IReadOnlyList<SyncTombstone> baseTombstones,
        DateTimeOffset? syncLast,
        DateTimeOffset now)
    {
        var result = new SyncMergeResult();
        var baseCutoff = (syncLast ?? DateTimeOffset.MinValue) + SkewTolerance;

        // Highest tombstone wins per id.
        var tombstones = new Dictionary<string, SyncTombstone>();
        foreach (var t in localTombstones) Absorb(tombstones, t);
        foreach (var t in baseTombstones) Absorb(tombstones, t);

        var localEntryById = localEntries.ToDictionary(x => x.Entry.Id);
        var baseEntryById = baseEntries.ToDictionary(x => x.Id);

        foreach (var id in localEntryById.Keys.Union(baseEntryById.Keys))
        {
            localEntryById.TryGetValue(id, out var l);
            baseEntryById.TryGetValue(id, out var b);
            tombstones.TryGetValue(id, out var t);
            var lTime = l?.Entry.UpdatedAt;
            var bTime = b?.UpdatedAt;
            var tTime = t?.DeletedAt;
            var latest = Max(lTime, bTime);

            // Tombstone newer than every surviving copy -> delete (or keep tombstone for the missing side).
            if (t is not null && (latest is null || tTime > latest))
            {
                if (l is not null) result.EntryIdsToDelete.Add(id);
                result.Tombstones.Add(t);
                result.Changed = true;
                continue;
            }

            // Tombstone older than the newest edit -> resurrection; the tombstone is dropped.
            if (t is not null) result.Changed = true;

            if (l is not null && b is null)
            {
                result.Entries.Add(l);
                result.Changed = true;
            }
            else if (b is not null && l is null)
            {
                if (b.UpdatedAt > baseCutoff)
                {
                    result.Entries.Add(ToLocal(b));
                    result.Changed = true;
                }
                else
                {
                    // Known previously, absent now -> deleted locally.
                    result.Tombstones.Add(new SyncTombstone { Id = id, Kind = TombstoneKind.Entry, DeletedAt = now });
                    result.Changed = true;
                }
            }
            else if (b!.UpdatedAt > l!.Entry.UpdatedAt)
            {
                result.Entries.Add(ToLocal(b));
                result.Changed = true;
            }
            else
            {
                result.Entries.Add(l);
                if (l.Entry.UpdatedAt != b.UpdatedAt) result.Changed = true;
            }
        }

        var localFolderById = localFolders.ToDictionary(x => x.Id);
        var baseFolderById = baseFolders.ToDictionary(x => x.Id);

        foreach (var id in localFolderById.Keys.Union(baseFolderById.Keys))
        {
            localFolderById.TryGetValue(id, out var l);
            baseFolderById.TryGetValue(id, out var b);
            tombstones.TryGetValue(id, out var t);
            var latest = Max(l?.UpdatedAt, b?.UpdatedAt);

            if (t is not null && (latest is null || t.DeletedAt > latest))
            {
                if (l is not null) result.FolderIdsToDelete.Add(id);
                result.Tombstones.Add(t);
                result.Changed = true;
                continue;
            }

            if (t is not null) result.Changed = true;

            if (l is not null && b is null)
            {
                result.Folders.Add(l);
                result.Changed = true;
            }
            else if (b is not null && l is null)
            {
                if (b.UpdatedAt > baseCutoff)
                {
                    result.Folders.Add(ToLocalFolder(b));
                    result.Changed = true;
                }
                else
                {
                    result.Tombstones.Add(new SyncTombstone { Id = id, Kind = TombstoneKind.Folder, DeletedAt = now });
                    result.Changed = true;
                }
            }
            else if (b!.UpdatedAt > l!.UpdatedAt)
            {
                result.Folders.Add(ToLocalFolder(b));
                result.Changed = true;
            }
            else
            {
                result.Folders.Add(l);
                if (l.UpdatedAt != b.UpdatedAt) result.Changed = true;
            }
        }

        // Prune very old tombstones, sort deterministically.
        result.Tombstones = result.Tombstones
            .Where(t => now - t.DeletedAt <= TombstoneRetention)
            .OrderBy(t => t.Id)
            .ToList();

        return result;
    }

    // ============================= internals =============================

    private void Apply(SyncMergeResult merge)
    {
        foreach (var folder in merge.Folders)
            _db.UpsertFolder(folder);

        foreach (var item in merge.Entries)
        {
            if (item.Entry.SecureBlob.Length == 0 && item.Payload is not null)
                _db.AssignSecureData(item.Entry, item.Payload);
            _db.UpsertEntry(item.Entry);
        }

        foreach (var id in merge.FolderIdsToDelete)
            _db.DeleteFolder(id);
        foreach (var id in merge.EntryIdsToDelete)
            _db.DeleteEntry(id);

        SaveTombstones(merge.Tombstones);
    }

    private List<SyncTombstone> LoadTombstones()
    {
        var json = _db.GetMeta(TombstonesKey);
        if (string.IsNullOrEmpty(json)) return new List<SyncTombstone>();
        try
        {
            var list = JsonSerializer.Deserialize<List<SyncTombstone>>(json, JsonOptions) ?? new List<SyncTombstone>();
            return list.Where(t => DateTimeOffset.UtcNow - t.DeletedAt <= TombstoneRetention).ToList();
        }
        catch
        {
            return new List<SyncTombstone>();
        }
    }

    private void SaveTombstones(IReadOnlyList<SyncTombstone> tombstones)
    {
        if (tombstones.Count == 0)
        {
            _db.DeleteMeta(TombstonesKey);
            return;
        }

        var valid = tombstones
            .Where(t => DateTimeOffset.UtcNow - t.DeletedAt <= TombstoneRetention)
            .OrderBy(t => t.Id)
            .ToList();
        _db.SetMeta(TombstonesKey, JsonSerializer.Serialize(valid, JsonOptions));
    }

    private SyncSnapshot BuildSnapshot(SyncMergeResult merge, string deviceId, DateTimeOffset now)
    {
        var entries = merge.Entries
            .OrderBy(x => x.Entry.Id)
            .Select(x => new SyncEntry
            {
                Id = x.Entry.Id,
                Kind = x.Entry.Kind.ToString().ToLowerInvariant(),
                Name = x.Entry.Name,
                Brand = x.Entry.Brand,
                Accent = x.Entry.Accent,
                Tags = x.Entry.Tags,
                FolderId = x.Entry.FolderId,
                CreatedAt = x.Entry.CreatedAt,
                UpdatedAt = x.Entry.UpdatedAt,
                Card = EntryKinds.IsCard(x.Entry.Kind) ? x.Payload as CardSecureData : null,
                Generic = !EntryKinds.IsCard(x.Entry.Kind) ? x.Payload as EntrySecureData : null,
            })
            .ToList();

        var folders = merge.Folders
            .OrderBy(x => x.Id)
            .Select(x => new SyncFolder
            {
                Id = x.Id,
                ParentId = x.ParentId,
                Name = x.Name,
                Icon = x.Icon,
                CreatedAt = x.CreatedAt,
                UpdatedAt = x.UpdatedAt,
            })
            .ToList();

        return new SyncSnapshot
        {
            DeviceId = deviceId,
            WrittenAt = now,
            Entries = entries,
            Folders = folders,
            Tombstones = merge.Tombstones,
        };
    }

    private SyncSnapshot Decode(byte[] file)
    {
        var env = JsonSerializer.Deserialize<SyncEnvelope>(file, JsonOptions)
            ?? throw new SyncException("The sync file is not a valid CardVault snapshot.");
        if (env.Magic != Magic || env.Version is < 1 or > FormatVersion)
            throw new SyncException("The sync file uses an unsupported format version.");
        if (string.IsNullOrEmpty(env.KdfSalt) || env.KdfIterations <= 0)
            throw new SyncException("The sync file is missing its encryption header.");

        var blob = Convert.FromBase64String(env.Blob ?? string.Empty);
        byte[] plain;
        try
        {
            plain = CryptoService.Decrypt(_syncKey ?? throw new SyncException("The vault is locked — unlock it first."), blob, SealContext);
        }
        catch
        {
            throw new SyncException(
                "Could not decrypt the sync snapshot. Both devices must use the same master password. " +
                "If the password changed on the other device, re-enable sync there first so this device can adopt the new key after re-unlocking.");
        }

        try
        {
            var snapshot = JsonSerializer.Deserialize<SyncSnapshot>(plain, JsonOptions) ?? new SyncSnapshot();
            foreach (var e in snapshot.Entries)
            {
                e.Card ??= new CardSecureData();
                e.Generic ??= new EntrySecureData();
            }
            return snapshot;
        }
        finally
        {
            CryptographicOperations.ZeroMemory(plain);
        }
    }

    private byte[] Encode(SyncSnapshot snapshot)
    {
        var key = _syncKey ?? throw new SyncException("The vault is locked — unlock it first.");
        var saltText = _db.GetMeta(SaltKey) ?? throw new SyncException("No sync key installed.");
        var iterations = int.TryParse(_db.GetMeta(IterKey), out var v) && v > 0 ? v : DefaultIterations;

        var plain = JsonSerializer.SerializeToUtf8Bytes(snapshot, JsonOptions);
        var blob = CryptoService.Encrypt(key, plain, SealContext);
        CryptographicOperations.ZeroMemory(plain);

        var envelope = new SyncEnvelope
        {
            Magic = Magic,
            Version = FormatVersion,
            KdfSalt = saltText,
            KdfIterations = iterations,
            Blob = Convert.ToBase64String(blob),
        };

        return JsonSerializer.SerializeToUtf8Bytes(envelope, JsonOptions);
    }

    private static void WriteAtomically(string path, byte[] bytes)
    {
        var temp = path + ".tmp";
        File.WriteAllBytes(temp, bytes);
        try
        {
            File.Move(temp, path, overwrite: true);
        }
        catch
        {
            File.Copy(temp, path, overwrite: true);
            File.Delete(temp);
        }
    }

    private string DeviceId()
    {
        var id = _db.GetMeta(DeviceKey);
        if (!string.IsNullOrEmpty(id)) return id;
        id = Guid.NewGuid().ToString("N");
        _db.SetMeta(DeviceKey, id);
        return id;
    }

    private async Task OnTickAsync()
    {
        if (_session.Key is null || _syncKey is null) return;
        var prefs = ReadPrefs();
        if (!prefs.Enabled || string.IsNullOrWhiteSpace(prefs.Folder)) return;
        try { await RunSyncAsync(); }
        catch { /* error is captured in LastError */ }
    }

    private void OnLocked()
    {
        ReleaseKey();
        LastError = string.Empty;
    }

    private void ReleaseKey()
    {
        if (_syncKey is not null) CryptographicOperations.ZeroMemory(_syncKey);
        _syncKey = null;
    }

    private static LocalItem ToLocal(SyncEntry b) => new(
        new VaultEntry
        {
            Id = b.Id,
            Kind = Enum.TryParse<EntryKind>(b.Kind, true, out var k) ? k : EntryKind.Card,
            Name = b.Name,
            Brand = b.Brand,
            Accent = b.Accent,
            Tags = b.Tags,
            FolderId = b.FolderId,
            CreatedAt = b.CreatedAt,
            UpdatedAt = b.UpdatedAt,
        },
        CardOr(b));

    private static object? CardOr(SyncEntry b)
    {
        var isCard = Enum.TryParse<EntryKind>(b.Kind, true, out var k) && EntryKinds.IsCard(k);
        return isCard ? (object?)b.Card : b.Generic;
    }

    private static Folder ToLocalFolder(SyncFolder b) => new()
    {
        Id = b.Id,
        ParentId = b.ParentId,
        Name = b.Name,
        Icon = b.Icon,
        CreatedAt = b.CreatedAt,
        UpdatedAt = b.UpdatedAt,
    };

    private static void Absorb(Dictionary<string, SyncTombstone> into, SyncTombstone t)
    {
        if (into.TryGetValue(t.Id, out var cur))
        {
            if (t.DeletedAt > cur.DeletedAt) into[t.Id] = t;
        }
        else
        {
            into[t.Id] = t;
        }
    }

    private static DateTimeOffset? Max(DateTimeOffset? a, DateTimeOffset? b)
    {
        if (a is null) return b;
        if (b is null) return a;
        return a > b ? a : b;
    }

    private static DateTimeOffset? ParseTimestamp(string? value) =>
        DateTimeOffset.TryParse(value, null, System.Globalization.DateTimeStyles.RoundtripKind, out var dto) ? dto : null;
}

/// <summary>User-configured sync state, persisted in the vault's meta table.</summary>
public sealed record SyncPrefs(string Folder, bool Enabled, DateTimeOffset? LastSync);

/// <summary>Thrown for user-facing sync failures (invalid file, wrong master password, ...).</summary>
public sealed class SyncException : Exception
{
    public SyncException(string message) : base(message) { }
}

internal static class TombstoneKind
{
    public const string Entry = "entry";
    public const string Folder = "folder";
}

internal sealed class LocalItem
{
    public LocalItem(VaultEntry entry, object? payload)
    {
        Entry = entry;
        Payload = payload;
    }

    public VaultEntry Entry { get; }
    public object? Payload { get; }
}

internal sealed class SyncMergeResult
{
    public List<LocalItem> Entries { get; } = new();
    public List<Folder> Folders { get; } = new();
    public List<SyncTombstone> Tombstones { get; set; } = new();
    public List<string> EntryIdsToDelete { get; } = new();
    public List<string> FolderIdsToDelete { get; } = new();
    public bool Changed { get; set; }
}

internal sealed class SyncSnapshot
{
    public string DeviceId { get; set; } = string.Empty;
    public DateTimeOffset WrittenAt { get; set; }
    public List<SyncEntry> Entries { get; set; } = new();
    public List<SyncFolder> Folders { get; set; } = new();
    public List<SyncTombstone> Tombstones { get; set; } = new();
}

internal sealed class SyncEntry
{
    public string Id { get; set; } = string.Empty;
    public string Kind { get; set; } = "card";
    public string Name { get; set; } = string.Empty;
    public string Brand { get; set; } = string.Empty;
    public int Accent { get; set; } = -1;
    public string Tags { get; set; } = string.Empty;
    public string FolderId { get; set; } = string.Empty;
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
    public CardSecureData? Card { get; set; }
    public EntrySecureData? Generic { get; set; }
}

internal sealed class SyncFolder
{
    public string Id { get; set; } = string.Empty;
    public string ParentId { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Icon { get; set; } = "folder";
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
}

internal sealed class SyncTombstone
{
    public string Id { get; set; } = string.Empty;
    public string Kind { get; set; } = TombstoneKind.Entry;
    public DateTimeOffset DeletedAt { get; set; }
}

internal sealed class SyncEnvelope
{
    public string Magic { get; set; } = string.Empty;
    public int Version { get; set; }
    public string KdfSalt { get; set; } = string.Empty;
    public int KdfIterations { get; set; }
    public string Blob { get; set; } = string.Empty;
}